### ISSUE TITLE
Superfluous column in file?

### ISSUE THREAD

**Issue by nullmightybofo** [katkost/MazurkaBL#2]
Hi!

I noticed that this file:

beat_time/M24-2beat_time.csv 

has an extra first column (with some performance directives).
Is that intended? I haven't checked whethter any of the other files have such an extra column, but the ones I've seen so far do not.

Thanks and BR!

**Comment by nullmightybofo** [comment]
This one also has an additional first column:

M63-3beat_time.csv

**Comment by katkost** [comment]
Thank you! I removed the column in both files.
